name: Monitor PDS Status (Alternative)

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run PDS Monitoring
        run: python monitor_pds.py
        
      - name: Create Pull Request with Results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add PDS monitoring results - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          title: "Add PDS monitoring results"
          body: "Automated monitoring results from GitHub Actions"
          branch: update-monitoring-results
          delete-branch: true
