name: Monitor PDS Status

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run PDS Monitoring
        env:
          PDS_URL: ${{ secrets.PDS_URL }}
          BLUESKY_USER: ${{ secrets.BLUESKY_USER }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: python monitor_pds.py
        
      - name: Commit and Push Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add the results file and analysis graphs
          git add results/pds_monitoring_data.json
          git add analysis/*.png
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add PDS monitoring results - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
